### ISSUE TITLE
Use Node Red

### ISSUE THREAD

**Issue by dkowis** [billimek/home-assistant-config#22]
Seriously, it's so much more awesome for automation.

**Comment by billimek** [comment]
See 

* https://flows.nodered.org/node/node-red-contrib-home-assistant
* https://community.home-assistant.io/t/reliable-multi-user-distributed-bluetooth-occupancy-presence-detection/50674
* https://www.reddit.com/r/homeassistant/comments/7c5v63/anyone_else_using_nodered_with_home_assistant/
* https://diyfuturism.com/index.php/2017/11/26/the-open-source-smart-home-getting-started-with-home-assistant-node-red/
* https://hub.docker.com/r/nodered/node-red-docker/ (use `v8` or `slim-v8` tag)

for some details

**Comment by dkowis** [comment]
Hm, I suppose I could run node-red on a different host than the RPi. I didn't really think about that. That might help with performance and stuff.

**Comment by billimek** [comment]
Have the node-red server running and behind auth.  Got basic concepts down and can see events from hass.  Need to find some good examples to move all of the automations out of hass and into node-red.

Will probably start with camera switching stuff, as it's really complicated to do in the hass YML:

* Auto switching based on sunruse/sunset
* Auto switching based on wind speed
* Auto switching based on prescense
* Auto switching based on 10pm cuttoff at night

All of these need to work together so it's a lot of duplication in the config to do it the HASS way.  I expect this to be a lot more straight-forward in node red

**Comment by dkowis** [comment]
Did you set up node-red on a different host than the RPi?

**Comment by billimek** [comment]
I'm actually running Home Assistant and Node Red as different docker containers on a VM where I run all my docker stuff.  

On the node-red server, when I configure the Home Assistant server connection info, I simply refer to the home assistant container name (`home-assistant`) in the connection information (`http://home-assistant:8133`) because they are sharing the same docker network.

This is how I run the node-red server container:

```
docker run \
    -d \
    --name node-red \
    --restart=always \
    --network=traefik \
    -p 1880:1880 \
    -e PUID=1001 -e PGID=1001 \
    -e TZ='America/New York' \
    -v /appdata/node-red:/data \
    --label=traefik.frontend.rule=Host:<redacted> \
    --label=traefik.port=1880 \
    --label='traefik.frontend.auth.basic=<redacted>' \
    nodered/node-red-docker:v8
fi
```

**Comment by billimek** [comment]
Done via https://github.com/billimek/k8s-gitops/blob/master/deployments/node-red.yaml
